# Generated by Django 4.0.4 on 2022-06-17 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_donaciones_delete_civil_delete_curso_delete_genero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donaciones',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
