# Generated by Django 4.0.4 on 2022-06-17 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_donaciones_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=100, verbose_name='Producto')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad de Productos')),
                ('rut', models.CharField(max_length=100, verbose_name='Rut')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('metodo', models.CharField(max_length=100, verbose_name='Metodo de pago')),
                ('tarjeta', models.CharField(max_length=100, verbose_name='Tarjeta')),
                ('fecha_expira', models.CharField(max_length=100, verbose_name='Fecha de expiración')),
                ('cvv', models.IntegerField(verbose_name='CVV')),
                ('direccion', models.CharField(max_length=100, verbose_name='Dirección')),
            ],
        ),
    ]
