# Generated by Django 4.0.4 on 2022-06-17 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='fecha_expira',
            new_name='fecha',
        ),
    ]
