# Generated by Django 4.0.4 on 2022-06-18 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_productostock'),
    ]

    operations = [
        migrations.AddField(
            model_name='personas',
            name='suscripcion',
            field=models.BooleanField(null=True, verbose_name='Suscripción'),
        ),
    ]
