# Generated by Django 4.0.4 on 2022-06-18 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_personas_suscripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas',
            name='suscripcion',
            field=models.CharField(max_length=100, verbose_name='Suscripción'),
        ),
    ]
