# Generated by Django 4.0.4 on 2022-06-18 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_personas_suscripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='id',
        ),
        migrations.AddField(
            model_name='producto',
            name='boleta',
            field=models.IntegerField(default=1, primary_key=True, serialize=False, verbose_name='Boleta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_efetuada',
            field=models.CharField(default=1, max_length=100, verbose_name='Fecha Efectuada'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='total',
            field=models.IntegerField(default=2, verbose_name='Total de Boleta'),
            preserve_default=False,
        ),
    ]
