# Generated by Django 4.0.4 on 2022-06-18 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_producto_id_producto_boleta_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='fecha_efetuada',
            new_name='fecha_efectuada',
        ),
    ]
