# Generated by Django 4.0.4 on 2022-06-30 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_fundacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productostock',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Id Producto'),
        ),
    ]
